### ISSUE TITLE
Cannot RegisterClass CustomNode

### ISSUE THREAD

**Issue by ZerxZ** [raulsntos/godot-dotnet#2]
### Godot version

Godot v4.3.dev5

### Godot .NET packages version

Godot v4.3.dev5.mono

### System information

Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.5123) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### .NET information

8.0.202

### Issue description

Cannot RegisterClass CustomNode

### Steps to reproduce

Build Sample Summator

### Minimal reproduction project

[CustomNodeMRP.zip](https://github.com/raulsntos/godot-dotnet/files/14891990/CustomNodeMRP.zip)

**Comment by raulsntos** [comment]
Can you describe the error in more detail? For example, are you getting any errors? Also, please try with the latest nightly packages (version is `4.3.0-nightly.24260.1`), I've recently fixed some marshalling/memory issues so if it was related maybe it solved your issue.

**Comment by ZerxZ** [comment]
This PR has been fixed  #3 .
![image](https://github.com/raulsntos/godot-dotnet/assets/71170059/2a9b9110-3bc5-4053-94db-7d291b4462e4)
https://github.com/raulsntos/godot-dotnet/blob/3e6de8d604389eec0f886b08d61a2a0507921d91/src/Godot.Bindings/NativeInterop/Marshalling.Ptr.cs#L12

Here the value parameter of the function may have a null value causing a crash.

**Comment by raulsntos** [comment]
Thanks for the detailed report.

I wonder what's the type `T` when the crash happens, unfortunately the error log doesn't provide much information. There were some recent fixes for nullable values when `T` is Array, Dictionary or StringName. The only other type that could be null there are the Packed Arrays, I'm not currently checking if those are null, I'm not sure if it's valid to receive null Packed Arrays in this method.

**Comment by ZerxZ** [comment]
> Thanks for the detailed report.
> 
> I wonder what's the type `T` when the crash happens, unfortunately the error log doesn't provide much information. There were some recent fixes for nullable values when `T` is Array, Dictionary or StringName. The only other type that could be null there are the Packed Arrays, I'm not currently checking if those are null, I'm not sure if it's valid to receive null Packed Arrays in this method.

I tried changing it to build the same as that pr with the latest branch, but it seems to be failing. Not sure what's wrong there now.

**Comment by raulsntos** [comment]
The Packed Array marshalling issue should be fixed by b62bb9c71c027193f6ef09d5c7028360f66c38ec. Are there any other issues reported here or can it be closed?

**Comment by ZerxZ** [comment]
My simple test did solve the inheritance problem. But I'm not sure about the rest. I've solved the problem by turning off the Issues.
