### ISSUE TITLE
Source generator may attempt to register child class before parent class

### ISSUE THREAD

**Issue by ArchercatNEO** [raulsntos/godot-dotnet#24]
### Godot version

4.3.stable.nixpkgs.77dcf97d8

### Godot .NET packages version

6bd7581

### System information

NixOS 24.11

### .NET information

9.0.100-rc.1.24452.12

### Issue description

When using the source generator and inheriting from a [GodotClass] the source generator registers classes in an arbitrary order which may lead to child classes being registered before their parents and therefore failing to become registered into ClassDB

### Steps to reproduce

Create a parent class annotated with [GodotClass]
Create a child class that inherits from the parent class annotated with [GodotClass]
Main.generated.cs may place the parent class after the child class which will fail

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
Thanks for the report!

You are right, currently the EntryPoint generator doesn't attempt to sort the classes to register in any way, so it's very likely that they'll be registered in the wrong order.

As a workaround you can disable the entry point generation with the `DisableGodotEntryPointGeneration` attribute:

```csharp
[assembly: DisableGodotEntryPointGeneration]
```

Then you can write the entry point yourself, you can see an example in the [Summator sample](https://github.com/raulsntos/godot-dotnet/blob/6bd7581727ca2e4b6e82e6775060d874215313ce/samples/Summator/Extension/Main.cs).
